/*
Package tutorial is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /home/raphael/go/src/github.com/openconfig/ygot/genutil/names.go
using the following YANG input files:
	- demo-port.yang
Imported modules were sourced from:
*/
package tutorial

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)


// E_DemoPort_SPEED is a derived int64 type which is used to represent
// the enumerated node DemoPort_SPEED. An additional value named
// DemoPort_SPEED_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_DemoPort_SPEED int64

// IsYANGGoEnum ensures that DemoPort_SPEED implements the yang.GoEnum
// interface. This ensures that DemoPort_SPEED can be identified as a
// mapped type for a YANG enumeration.
func (E_DemoPort_SPEED) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  DemoPort_SPEED.
func (E_DemoPort_SPEED) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

const (
	// DemoPort_SPEED_UNSET corresponds to the value UNSET of DemoPort_SPEED
	DemoPort_SPEED_UNSET E_DemoPort_SPEED = 0
	// DemoPort_SPEED_SPEED_10GB corresponds to the value SPEED_10GB of DemoPort_SPEED
	DemoPort_SPEED_SPEED_10GB E_DemoPort_SPEED = 1
)

