import demo_port as demo_port
import yaml
import os
import pyangbind.lib.pybindJSON as pybindJSON


MODEL_NAME = "demo_port"
EXAMPLE_DIR = "examples/"


def load_serialize_model():
    """
    Open a given YAML file and tries to load it into
    model that was generated by pyangbind.
    Fails if the YAML file is not compatible to the
    model.
    """

    example_demo_ports = os.listdir(EXAMPLE_DIR)
    ep = example_demo_ports[0]
    yaml_path = os.path.join(EXAMPLE_DIR, ep)

    with open(yaml_path, "r") as f:
        demo_port_data = yaml.load(f, Loader=yaml.FullLoader)
        demo_port_model = pybindJSON.loads_ietf(
            demo_port_data, demo_port, MODEL_NAME)


        # Modifying the source model - adds a new port and sets its config
        port = demo_port_model.ports.port.add(2)
        port.config.speed = "SPEED_10GB"
        print(pybindJSON.dumps(demo_port_model))


if __name__ == "__main__":
    load_serialize_model()
