/*
Package tutorial is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /home/raphael/go/src/github.com/openconfig/ygot/genutil/names.go
using the following YANG input files:
	- demo-port.yang
Imported modules were sourced from:
*/
package tutorial

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)


// DemoPort_Ports represents the /demo-port/ports YANG schema element.
type DemoPort_Ports struct {
	Port	map[uint16]*DemoPort_Ports_Port	`path:"port" module:"demo-port"`
}

// IsYANGGoStruct ensures that DemoPort_Ports implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DemoPort_Ports) IsYANGGoStruct() {}


// DemoPort_Ports_Port represents the /demo-port/ports/port YANG schema element.
type DemoPort_Ports_Port struct {
	Config	*DemoPort_Ports_Port_Config	`path:"config" module:"demo-port"`
	PortNumber	*uint16	`path:"port-number" module:"demo-port"`
	State	*DemoPort_Ports_Port_State	`path:"state" module:"demo-port"`
}

// IsYANGGoStruct ensures that DemoPort_Ports_Port implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DemoPort_Ports_Port) IsYANGGoStruct() {}


// DemoPort_Ports_Port_Config represents the /demo-port/ports/port/config YANG schema element.
type DemoPort_Ports_Port_Config struct {
	Speed	E_DemoPort_SPEED	`path:"speed" module:"demo-port"`
}

// IsYANGGoStruct ensures that DemoPort_Ports_Port_Config implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DemoPort_Ports_Port_Config) IsYANGGoStruct() {}


// DemoPort_Ports_Port_State represents the /demo-port/ports/port/state YANG schema element.
type DemoPort_Ports_Port_State struct {
	Status	*bool	`path:"status" module:"demo-port"`
}

// IsYANGGoStruct ensures that DemoPort_Ports_Port_State implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DemoPort_Ports_Port_State) IsYANGGoStruct() {}


